version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  checkout:
    docker:
      - image: circleci/node:12.20.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install v1-dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build:
    docker:
      - image: circleci/node:12.20.0
    steps:
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker Image
          command: docker build -t michaelhettmer/docker-vscode-remote-latex .
      - run:
          name: Persist Docker Image
          command: docker save michaelhettmer/docker-vscode-remote-latex | gzip > docker_michaelhettmer_docker-vscode-remote-latex.tar.gz
      - persist_to_workspace:
          root: ~/project
          paths:
            - docker_michaelhettmer_docker-vscode-remote-latex.tar.gz

  release:
    docker:
      - image: circleci/node:12.20.0
    steps:
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Load Docker Image
          command: docker load -i docker_michaelhettmer_docker-vscode-remote-latex.tar.gz
      - run:
          name: Release Docker Image
          command: npx semantic-release

workflows:
  build:
    jobs:
      - checkout
      - docker/hadolint:
          requires:
            - checkout
          dockerfiles: Dockerfile
      - build:
          requires:
            - docker/hadolint
      - release:
          context: docker
          requires:
            - build
          filters:
            branches:
              only: master
